# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  1password: onepassword/secrets@1.0.0
steps:
    - 1password/install-cli:
        version: 2.18.0
    - checkout
    - run:
        shell: op run -- /bin/bash
        environment:
          AWS_ACCESS_KEY_ID: "op://cli-vault/aws/access credentials/username"
          AWS_SECRET_ACCESS_KEY: "op://cli-vault/aws/access credentials/password"
        command: |
          echo "This value will be masked: $AWS_ACCESS_KEY_ID"
          echo "This value will be masked: $AWS_SECRET_ACCESS_KEY"
          ./deploy-my-app.sh
        
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - say-hello
